## Introduction:


Grey Wolf Optimization (GWO) is a population-based metaheuristic optimization algorithm inspired by the social hierarchy and hunting mechanisms of grey wolves. It mimics the leadership hierarchy of alpha, beta, and gamma wolves to iteratively search for the optimal solution to a given problem. In this implementation, we'll walk through the code that performs the GWO algorithm to optimize a given objective function.



##1. Initialization:



In [1]:
import numpy as np

In [2]:
lb = -10  # Lower bound
ub = 10   # Upper bound
Np = 5    # Population size
max_iter = 5  # Maximum iterations

## 1.1 Objective function:


In [3]:
def objective_function(x1, x2, x3, x4):
    return x1**2 + x2**2 + x3**2 + x4**2


Fitness function is the same as objective because we are going to minimize, If the plan is to maximize, we would use: Fitness(x)= 1/(1+x^2)


## 1.2 Bound function:

In [4]:
def bound(x_new, lb, ub):
    return np.clip(x_new, lb, ub)

## 1.3 Initialize the population:

In [5]:
def initialize_population(lb, ub, Np, D):
    return np.random.uniform(low=lb, high=ub, size=(Np, D))

## 1.4 fitness function evaluation:


In [6]:
def evaluate_fitness(X, f):
    return np.array([f(*x) for x in X])

## 2. Funciton Update:

In [7]:
# Update the alpha, beta, and gamma wolves
def update_wolves(X, fitness):
    # Sort indices based on fitness values in ascending order
    sorted_indices = np.argsort(fitness)
    # Get indices for alpha, beta, and gamma wolves
    alpha_idx, beta_idx, gamma_idx = sorted_indices[0], sorted_indices[1], sorted_indices[2]
    # Get the corresponding wolves
    alpha, beta, gamma = X[alpha_idx], X[beta_idx], X[gamma_idx]
    # Get the corresponding fitness values
    alpha_fit, beta_fit, gamma_fit = fitness[alpha_idx], fitness[beta_idx], fitness[gamma_idx]
    return alpha, beta, gamma, alpha_fit, beta_fit, gamma_fit

##3. Calculate encircling behavior:


In [8]:
def calculate_encircling_behavior(a, X, alpha, beta, gamma, lb, ub):
    new_X = np.zeros_like(X)
    for i in range(len(X)):
        # Calculate X1 using alpha
        r1, r2 = np.random.rand(), np.random.rand()
        Ak = 2 * a * r1 - a
        Ck = 2 * r2
        D_alpha = np.abs(Ck * alpha - X[i])
        X1 = alpha - Ak * D_alpha

        # Calculate X2 using beta
        r1, r2 = np.random.rand(), np.random.rand()
        Ak = 2 * a * r1 - a
        Ck = 2 * r2
        D_beta = np.abs(Ck * beta - X[i])
        X2 = beta - Ak * D_beta

        # Calculate X3 using gamma
        r1, r2 = np.random.rand(), np.random.rand()
        Ak = 2 * a * r1 - a
        Ck = 2 * r2
        D_gamma = np.abs(Ck * gamma - X[i])
        X3 = gamma - Ak * D_gamma

        # Calculate the new position
        new_X[i] = (X1 + X2 + X3) / 3
        # Bound the new position
        new_X[i] = bound(new_X[i], lb, ub)

    return new_X

## 3. GWO algorithm:


In [9]:
def gwo_algorithm(f, lb, ub, Np, max_iter):
    D = 4  # Dimension of the problem (x1, x2, x3, x4)

    # Initialize the population randomly
    X = initialize_population(lb, ub, Np, D)
    fitness = evaluate_fitness(X, f)

    for iteration in range(max_iter):
        # Print iteration details
        print(f"[$]Iteration: {iteration+1}")
        print("="*55)
        print("\tPopulation\t |\t  Objective Values\t")
        print("="*55)
        for i in range(Np):
            print(f"{np.around(X[i], decimals=2)}| \t\t{round(f(*X[i]), 2)}\t")
        print("="*55)

        # Update alpha, beta, and gamma wolves
        alpha, beta, gamma, alpha_fit, beta_fit, gamma_fit = update_wolves(X, fitness)

        # Calculate encircling behavior
        a = 1.0               # constant between 0 and 2
        X = calculate_encircling_behavior(a, X, alpha, beta, gamma, lb, ub)

        # Evaluate the new fitness
        fitness = evaluate_fitness(X, f)

        print(f"\nAlpha->\t{np.around(alpha, decimals=2)},\tFitness: {round(alpha_fit, 2)}")
        print(f"Beta->\t{np.around(beta, decimals=2)},\tFitness: {round(beta_fit, 2)}")
        print(f"Gamma->\t{np.around(gamma, decimals=2)},\tFitness: {round(gamma_fit, 2)}\n")
        print("~"*55)

    return alpha, alpha_fit

## 4. Main function:


In [10]:
def main():
    # Run GWO algorithm
    gwo_algorithm(objective_function, lb, ub, Np, max_iter)


In [11]:
if __name__ == "__main__":
    main()

[$]Iteration: 1
	Population	 |	  Objective Values	
[-5.91 -1.67  9.03  8.21]| 		186.81	
[-0.15  0.28 -9.52  8.94]| 		170.77	
[ 6.16 -4.99  8.07  9.06]| 		210.0	
[ 8.92 -5.24 -1.16 -2.14]| 		112.94	
[5.19 7.96 3.21 4.87]| 		124.36	

Alpha->	[ 8.92 -5.24 -1.16 -2.14],	Fitness: 112.94
Beta->	[5.19 7.96 3.21 4.87],	Fitness: 124.36
Gamma->	[-0.15  0.28 -9.52  8.94],	Fitness: 170.77

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[$]Iteration: 2
	Population	 |	  Objective Values	
[8.04 2.25 1.56 7.03]| 		121.5	
[ 5.45  0.82 -5.08  3.22]| 		66.58	
[ 4.48 -3.58 -3.03  1.18]| 		43.43	
[ 3.49 -0.95 -2.75  3.35]| 		31.88	
[ 3.21 -0.65 -8.98  0.55]| 		91.66	

Alpha->	[ 3.49 -0.95 -2.75  3.35],	Fitness: 31.88
Beta->	[ 4.48 -3.58 -3.03  1.18],	Fitness: 43.43
Gamma->	[ 5.45  0.82 -5.08  3.22],	Fitness: 66.58

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[$]Iteration: 3
	Population	 |	  Objective Values	
[ 5.29 -0.95 -2.24  3.37]| 		45.21	
[ 2.76 -2.36 -5.45  1.34]| 		44.74	
[ 5.25